<?php

/*********************
 * ACF
 *********************/

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_5883f8203079e',
        'title' => 'Horaires',
        'fields' => array (
            array (
                'key' => 'field_5883f83b44d90',
                'label' => 'Horaires',
                'name' => 'horaires',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '',
                'layout' => 'table',
                'button_label' => 'Ajouter un élément',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5883f85344d91',
                        'label' => 'Jour',
                        'name' => 'jour',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883f85944d92',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883f87044d93',
                        'label' => 'Lieu',
                        'name' => 'lieu',
                        'type' => 'text',
                        'instructions' => 'Uniquement pour le camion',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
                array (
                    'param' => 'page',
                    'operator' => '!=',
                    'value' => '4',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
    acf_add_local_field_group(array (
        'key' => 'group_5883f8203079d',
        'title' => 'Téléphone',
        'fields' => array (
            array (
                'key' => 'field_5883f89744d94',
                'label' => 'Numéro de téléphone',
                'name' => 'numero_de_telephone',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '7',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
    acf_add_local_field_group(array (
        'key' => 'group_5883f8203079f',
        'title' => 'Adresse',
        'fields' => array (
            array (
                'key' => 'field_5883f82644d8f',
                'label' => 'Adresse',
                'name' => 'adresse',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '7',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_5883c457cf1b5',
        'title' => 'Options',
        'fields' => array (
            array (
                'key' => 'field_5883c64a0b525',
                'label' => 'Suppression éléments sidebar',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_5883c45d4e3f9',
                'label' => 'Affichage',
                'name' => 'affichage',
                'type' => 'checkbox',
                'instructions' => 'Séléctionner les éléments de la sidebar à cacher',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array (
                    'index.php' => 'Tableau de bord',
                    'edit.php' => 'Articles',
                    'edit.php?post_type=page' => 'Pages',
                    'upload.php' => 'Médias',
                    'users.php' => 'Utilisateurs',
                    'tools.php' => 'Options',
                    'themes.php' => 'Apparence',
                    'options-general.php' => 'Réglages',
                    'edit.php?post_type=camion' => 'ACF - Camion',
                    'edit.php?post_type=restaurant' => 'ACF - Restaurant',
                    'edit-comments.php' => 'Commentaires',
                    'plugins.php' => 'Extensions',
                    'edit.php?post_type=acf-field-group' => 'ACF',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
            ),
            array (
                'key' => 'field_5883c65a0b526',
                'label' => 'Ajout éléments sidebar',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_5883c6750b527',
                'label' => 'Icone',
                'name' => 'icone',
                'type' => 'repeater',
                'instructions' => '<a href="https://developer.wordpress.org/resource/dashicons/">Liste des icones disponibles sur Wordpress</a>',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5883c6880b528',
                'min' => '',
                'max' => '',
                'layout' => 'block',
                'button_label' => 'Ajouter un élément',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5883c6880b528',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Navigation',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883c69a0b529',
                        'label' => 'Titre sidebar',
                        'name' => 'titre_sidebar',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Navigation',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883c6ab0b52a',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'type' => 'text',
                        'instructions' => 'Lien pour la redirection ( fichier php )',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'nav-menus.php',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883c6d90b52b',
                        'label' => 'Icone',
                        'name' => 'icone',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'dashicons-menu',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883c7010b52c',
                        'label' => 'Position',
                        'name' => 'position',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 2,
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array (
                        'key' => 'field_5883e657b50c0',
                        'label' => 'Sous menu',
                        'name' => 'sous_menu',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                    ),
                    array (
                        'key' => 'field_5883ed4c07fa4',
                        'label' => 'Nom',
                        'name' => 'subpage_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array (
                            array (
                                array (
                                    'field' => 'field_5883e657b50c0',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5883ed4507fa3',
                        'label' => 'Id',
                        'name' => 'id',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array (
                            array (
                                array (
                                    'field' => 'field_5883e657b50c0',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-back-office',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_5883f9d829416',
        'title' => 'Pages',
        'fields' => array (
            array (
                'key' => 'field_5883efb8991ce',
                'label' => 'Le restaurant',
                'name' => 'restaurant',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'page',
                ),
                'taxonomy' => array (
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'id',
                'ui' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-pages',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_5883b4aff1a4e',
        'title' => 'Prix',
        'fields' => array (
            array (
                'key' => 'field_5883b4caf5162',
                'label' => 'Prix',
                'name' => 'prix',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '00.00',
                'prepend' => '',
                'append' => '€',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'camion',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'restaurant',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_5883bc781e28a',
        'title' => 'Prix formules',
        'fields' => array (
            array (
                'key' => 'field_5883d2a932af1',
                'label' => 'Avec boisson',
                'name' => 'prix_boisson',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '00.00',
                'prepend' => '',
                'append' => '€',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_5883d2bc32af2',
                'label' => 'Avec dessert',
                'name' => 'prix_dessert',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '00.00',
                'prepend' => '',
                'append' => '€',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'camion',
                ),
                array (
                    'param' => 'post_taxonomy',
                    'operator' => '==',
                    'value' => 'type:formule',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'restaurant',
                ),
                array (
                    'param' => 'post_taxonomy',
                    'operator' => '==',
                    'value' => 'type:formule',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_5883cc0004e98',
        'title' => 'Séparations',
        'fields' => array (
            array (
                'key' => 'field_5883ca527bd3a',
                'label' => 'Séparation',
                'name' => 'separation',
                'type' => 'true_false',
                'instructions' => 'Séparer les éléments des menus avec des images',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Ajouter des images pour séparer les éléments',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_5883ca517bd39',
                'label' => 'Tous les',
                'name' => 'tous_les',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5883ca527bd3a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 3,
                'prepend' => '',
                'append' => 'éléments',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_5883ca4f7bd38',
                'label' => 'Images',
                'name' => 'images',
                'type' => 'gallery',
                'instructions' => 'Images pour les séparations',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5883ca527bd3a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'insert' => 'append',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
                array (
                    'param' => 'page',
                    'operator' => '!=',
                    'value' => '4',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_5883f9877e13e',
        'title' => 'Social',
        'fields' => array (
            array (
                'key' => 'field_5883f8eb855cc',
                'label' => 'Facebook',
                'name' => 'facebook',
                'type' => 'url',
                'instructions' => 'Adresse facebook',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array (
                'key' => 'field_5883f90e855cd',
                'label' => 'Instagram',
                'name' => 'instagram',
                'type' => 'url',
                'instructions' => 'Adresse instagram',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-social',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;